const REFRESH_TOKEN_EXPIRATION = 3600 * 7 * 30;

export const JWT_EXPIRATION = 3600;
const MILLISECONDS_IN_SECOND = 1000;
export const JWT_EXPIRATION_IN_SECONDS = JWT_EXPIRATION * MILLISECONDS_IN_SECOND;
export const REFRESH_TOKEN_EXPIRATION_IN_SECONDS =
	REFRESH_TOKEN_EXPIRATION * MILLISECONDS_IN_SECOND;
